### ISSUE TITLE
Missing  scopes documentation for create_gdrive_folder.py

### ISSUE THREAD

**Issue by thekoma** [GoogleCloudPlatform/genai-for-marketing#134]
# When running this script you have to be logged with the right scopes with gcloud. 
Otherwise you will get a scopes error.

## Solution
I'd suggest to add this in the documentation:
```bash
gcloud auth application-default login \
--scopes='https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/drive'
```

## Error
This is the error so that users encapping in this situation can find this issue:
```log
python3 scripts/create_gdrive_folder.py --folder-name="genai-marketing-assets" --service-account-email=genai-marketing-run@genai-for-marketing-ID.iam.gserviceaccount.com
Using arguments: Namespace(folder_name='genai-marketing-assets', service_account_email='genai-marketing-run@genai-for-marketing-ID.iam.gserviceaccount.com')
genai-marketing-assets
Traceback (most recent call last):
  File "mypath/src/genai-for-marketing/infra/scripts/create_gdrive_folder.py", line 177, in <module>
    service.files()
  File "mypath/src/genai-for-marketing/infra/scripts/venv/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "mypath/src/genai-for-marketing/infra/scripts/venv/lib/python3.9/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v3/files?q=name%3D%27genai-marketing-assets%27&pageSize=10&fields=nextPageToken%2C+files%28id%2C+name%29&supportsAllDrives=true&includeItemsFromAllDrives=true&alt=json returned "Request had insufficient authentication scopes.". Details: "[{'message': 'Insufficient Permission', 'domain': 'global', 'reason': 'insufficientPermissions', 'debugInfo': 'Authentication error: 2; Error Details: {AuthType:7,ErrorCode:2,ServiceID:0,Scopes:[],BackendType:2,DebugInfo:gaia_mint_exchange::SCOPE_NOT_PERMITTED: None of the authentication credential token scopes [API_CLOUD_PLATFORM,API_SQLSERVICE_LOGIN,API_EMAIL,API_EMERALDSEA_ME] provided any of the desired scopes [API_GAIA_FILTER_BASE,API_DRIVE,API_DRIVE_APPDATA,API_DRIVE_RESOURCE,API_DRIVE_MEET_READONLY,API_DRIVE_METADATA,API_DRIVE_READONLY_METADATA,API_DRIVE_PHOTOS_READONLY,API_DRIVE_READONLY]}'}]">
```

**Comment by michaelwsherman** [comment]
Can you confirm this still happens if you do the full install via Cloud Shell?

**Comment by chmstimoteo** [comment]
@thekoma fixed this issue: https://github.com/GoogleCloudPlatform/genai-for-marketing/blob/main/infra/README.md by setting the right scopes as per the forum above.
